// Lokaler Platzhalter-Avatar als Inline-SVG. Ersetzt die frueher hartcodierte
// Cloudinary-URL eines fremden Accounts — kein externer Request mehr.
export const GUEST_IMG = 'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxMDAgMTAwIj48Y2lyY2xlIGN4PSI1MCIgY3k9IjUwIiByPSI1MCIgZmlsbD0iI2MzYzZkNCIvPjxjaXJjbGUgY3g9IjUwIiBjeT0iMzgiIHI9IjE3IiBmaWxsPSIjZmZmZmZmIi8+PHBhdGggZD0iTTE0IDkyYTM2IDM2IDAgMCAxIDcyIDB6IiBmaWxsPSIjZmZmZmZmIi8+PC9zdmc+'
